### ISSUE TITLE
Misrender of `--` em-dash (long dash) into `—-` (long dash followed by short dash) in semantic XML

### ISSUE THREAD

**Issue by ReesePlews** [metanorma/metanorma-ieee#373] opened 2024-06-02 01:30 UTC
we have some text in our document which is encoded as:

`...arbitrarily complex relationships -- including hierarchical, heterarchical, and nested -- is central to its role...`

the PDF is rendered as (notice the long dash followed immediately by a small dash (hyphen?):

![image](https://github.com/metanorma/metanorma-ieee/assets/35089343/596aff6a-c91b-4912-9a1d-c19a741cef47)

the MS-Word document is rendered as:

![image](https://github.com/metanorma/metanorma-ieee/assets/35089343/0342a637-e4c2-4bf1-97a6-484cc64491b8)

from reading the metanorma documentation i thought the em-dash (long dash) was encoded as `--` dashes
![image](https://github.com/metanorma/metanorma-ieee/assets/35089343/5aab6cda-f5ab-460c-b514-6c076bacf065)

@opoudjis could you tell me i am misinterpreting the method for creating the em-dash or if there is an issue with the tool. thank you.

**Comment by ronaldtse** [comment] 2024-06-02 02:14
I assume this is the PDF? Ping @Intelligent2013

**Comment by ReesePlews** [comment] 2024-06-02 02:23
thank you @ronaldtse and @opoudjis, i should have been more clear. the first image was the PDF, i have updated the original issue to now include output from MS-Word. i am not using the HTML output so i am not checking that, sorry.

**Comment by ronaldtse** [comment] 2024-06-02 02:29
@ReesePlews is it possible to provide the relevant XML output? That would quickly resolve any question of reproducibility and quicken the fix. Thanks!

**Comment by ronaldtse** [comment] 2024-06-02 05:24
The semtnaic XML is:

```xml
<p id="_f96eb3d4-1759-7e07-09a5-9aaa3e73f7c0">... navigate arbitrarily complex relationships —- including hierarchical, heterarchical, and nested —- is central to its role...</p>
```

Notice that the sequence of `—-` is already present. This is a bug.

**Comment by ronaldtse** [comment] 2024-06-02 05:40
Actually this is p a bug. The original encoding is:

```adoc
... navigate arbitrarily complex relationships --- including hierarchical, heterarchical, and nested --- is central to its role...
```

There are 3 dashes here. The first 2 dashes became an em-dash and the last one remains.

I checked the "fixed branch" and the encoding is correct:

https://github.com/Spatial-Web-Foundation/SWF-Corpus_and_IEEEP2874-D2/pull/1590

```adoc
<p id="_a03d7f45-491a-79c8-1bdd-f0c99444863f">... navigate arbitrarily complex relationships — including hierarchical, heterarchical, and nested — is central to its role...</p>
```

**Comment by ronaldtse** [comment] 2024-06-02 05:41
Closing, problem due to incorrect syntax.

**Closed by ronaldtse** 2024-06-02 05:41 UTC
Labels: bug
