### ISSUE TITLE
Mistaken authorship rendering in a bibliographic entry with multiple authors

### ISSUE THREAD

**Issue by ReesePlews** [metanorma/metanorma-ieee#281] opened 2023-06-22 12:14 UTC
presently this is a question:

if i create the .adoc bibliography file and add a bibliographic entry like below

> * [[[ferre-bigorra,1]]],
> span:initials[J.] span:surname[Ferré-Bigorra], 
> span:initials[M.] span:surname[Casals], 
> span:initials[G.] span:surname[Gangolells],
> span:type[book]
> span:title[The adoption of urban digital twins].
> span:type[inproceedings]
> In: span:in_title[Cities].
> vol. span:volume[131],
> pp. span:pages[103905],
> span:date[2022].
> doi: span:uri.doi[10.1016/j.cities.2022.103905].

will metanorma reformat the entry based on the correct "flavor" (in this case IEEE styling) or do i need to specifically modify the content in the "spans" to reflect a specific style requirement?

i am having some difficulty understanding the formatting output of the entries after the first author, and i am wondering if this is something i need to do, or if metanorma will do that automatically?

PDF (20230621 document generate: IEEE P2874)
![image](https://github.com/metanorma/metanorma-ieee/assets/35089343/f2b6d596-6e37-4836-af03-81d6708943be)

any advice or links to document would be most helpful. thank you

**Comment by ronaldtse** [comment] 2023-06-23 07:49
Thank you @ReesePlews for raising this!

The problem here is with:
* "Ferré-Bigorra, J. M., G. Casals, and Gangolells,"

It should have been:
* "Ferré-Bigorra, J., M. Casals, and G. Gangolells,"

The problem is that both the "J" and "M" was assigned to be the initials of "Ferré-Bigorra".

@opoudjis can you please help with this? Thanks.

**Comment by opoudjis** [comment] 2023-06-23 19:19
I will post updated advice on Metanorma.org. The story is simply, surname must always precede initials and given names. (It is implicit in the present wording, "After the first instances of surname and either initials or givenname," but I will make it explicit.) The relative ordering of initial and surname for the first and for subsequent names is determined by Metanorma's citation stylesheet.

So:

````
> * [[[ferre-bigorra,1]]],
> span:surname[Ferré-Bigorra], span:initials[J.] 
> span:surname[Casals], span:initials[M.] 
> span:surname[Gangolells], span:initials[G.] 
> span:type[book]
> span:title[The adoption of urban digital twins].
> span:type[inproceedings]
> In: span:in_title[Cities].
> vol. span:volume[131],
> pp. span:pages[103905],
> span:date[2022].
> doi: span:uri.doi[10.1016/j.cities.2022.103905].
````

**Closed** 2023-06-23 19:20 UTC
Labels: bug

**Comment by ReesePlews** [comment] 2023-06-24 03:58
@opoudjis thank you for the explanation. i am sorry i would like to confirm a bit more...

you said:  span:surname[Ferré-Bigorra], span:initials[J.] 

Q1 with surname before initials, however you have also added a comma between them and removed the comma at the end of the line; are those changes critical?

Q2 and is this format is for any bibliographic entry (with an author) in metanorma (across any template flavor)? i would assume any template flavor, but just want to confirm.

i will update my current bibliography after hearing from you.

thank you for checking this, and the other items.

**Comment by opoudjis** [comment] 2023-07-16 09:30
> Q1 with surname before initials, however you have also added a comma between them and removed the comma at the end of the line; are those changes critical?

No. Anything not contained inside a `span:[ ]` macro is in fact thrown out completely. The spans are there to convey the real information; extraneous text like punctuation are to make the input human-readable, but the actual formatting is completely governed by the organisation's bibliographic stylesheet.

> Q2 and is this format is for any bibliographic entry (with an author) in metanorma (across any template flavor)? i would assume any template flavor, but just want to confirm.

Yes, correct.

Once again, sorry it's taken me so long to respond, I've been on a semi-break from Metanorma last couple of weeks.

**Comment by ReesePlews** [comment] 2023-07-17 22:34
@opoudjis thank you for the confirmation on these two questions.  i will have a look to make sure the bibliography i am working on follows the structure guidelines.
