### ISSUE TITLE
terminology:  carriage retrun being added before xref term {{notation}}

### ISSUE THREAD

**Issue by ReesePlews** [metanorma/metanorma-ieee#175] opened 2022-11-13 12:05 UTC
looks like this is happening in both html and ms-word output...

`Operation on an {{hyperspace object}}.`

renders as 
![Spatial_Web_Protocol_Architecture_and_Governance_-_2022-11-13_20_48_49](https://user-images.githubusercontent.com/35089343/201520473-fe731fc4-31de-4d1f-8e45-b87dd10148f9.png)

grammar error has been corrected;

**Comment by ronaldtse** [comment] 2022-11-15 01:53
Thanks @ReesePlews , this has been fixed in #176 which will be released in 2 weeks.

**Comment by ronaldtse** [comment] 2022-11-15 02:01
This is how it looks like in the updated version (using Git gems). Thanks!

<img width="579" alt="Screen Shot 2022-11-15 at 10 01 30 AM" src="https://user-images.githubusercontent.com/11865/201808176-373291e0-b7d4-4f4c-926c-9bb1e6067b98.png">

**Closed** 2022-11-15 02:01 UTC

**Comment by ReesePlews** [comment] 2022-11-15 02:22
@ronaldtse thank you for checking this. i wonder why the xref in {{hyperspace object}} is not being linked? it could be an issue in my file, i will check.

**Comment by opoudjis** [comment] 2022-11-15 04:30
> @ronaldtse thank you for checking this. i wonder why the xref in {{hyperspace object}} is not being linked? it could be an issue in my file, i will check.

The term was not defined at all in the document I looked at. As the introductory paragraph says, the IEEE Standards Dictionary is assumed to hold for terms not defined in the document, so I don't insert an error message for the missing term in the document (I do in other flavours), but I do include the missing term in the error log.

So "hyperspace object" isn't cross-referenced because the document I saw gave nowhere to link it to.

**Comment by opoudjis** [comment] 2022-11-15 04:36
> Thanks @ReesePlews , this has been fixed in #176 which will be released in 2 weeks.

1 week in fact, as long as the release process doesn't blow up...

**Comment by ReesePlews** [comment] 2022-11-15 11:40
@opoudjis i see the issue now about the {{hyperspace object}} not being a defined term; sorry i did not pick up on that earlier; but thank you for the update;

**Comment by opoudjis** [comment] 2022-11-15 13:08
Like I say, we're in a bind, because we can't insert a "THIS IS A MISSING TERM" in the IEEE document: you can reference missing terms if they're in the IEEE Standards Dictionary.

We do report missing terms in the error log. The problem is, we report lots of things, most of which are false alarms.
