### ISSUE TITLE
Keywords are partially rendered

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-ieee#102] opened 2022-07-15 14:15 UTC
Taking https://github.com/metanorma/mn-samples-ieee-private/pull/9 as an example:

`````
:keywords: Automatic Test Markup Language (ATML), automatic test systems, Extensible Markup Language (XML), IEEE 1636.1, Software Interface for Maintenance Information Collection and Analysis (SIMICA), test results, XML schema
`````

In HTML, there are no *Keywords* rendered.

In DOC, keywords are not comma-separate:
![capture3-1](https://user-images.githubusercontent.com/33627611/179241074-75d38ffb-c54a-4bd5-a344-bd9c10fbb413.PNG)

In PDF, only the first keyword is rendered:
![capture3-2](https://user-images.githubusercontent.com/33627611/179241334-4b830e0b-bf10-47c9-92ab-bd07b6421e07.PNG)

**Comment by ronaldtse** [comment] 2022-07-15 16:23
Merged, thanks @Intelligent2013 !

**Comment by ronaldtse** [comment] 2022-07-15 16:43
Confirmed fixed.

<img width="505" alt="image" src="https://user-images.githubusercontent.com/11865/179269364-eef26ae5-e451-4a43-8d4e-16dd39c38725.png">

**Comment by manuelfuenmayor** [comment] 2022-07-15 20:32
@ronaldtse shouldn't the keywords be comma-separated instead of semicolon-separated?

**Comment by ronaldtse** [comment] 2022-07-16 03:15
@manuelfuenmayor yes you’re correct! Sorry for closing this ticket early. 

They should be separated by comma as shown in the style manual. 

Next time it would be more helpful if you could provide the screenshot here so we can reopen. Thanks!

**Comment by ronaldtse** [comment] 2022-07-16 03:16
From Style Manual. 

![httpsmentor ieee orgmyprojectPublicmytoolsdraftstyleman pdf](https://user-images.githubusercontent.com/11865/179337157-caf67fd2-9c36-4ba0-a9ea-128981696ded.png)

**Comment by Intelligent2013** [comment] 2022-07-16 06:18
> shouldn't the keywords be comma-separated instead of semicolon-separated?

@manuelfuenmayor could you point me to the document with the semicolon-separated keywords, please?

**Comment by ronaldtse** [comment] 2022-07-16 07:33
@Intelligent2013 I think @manuelfuenmayor meant that the keywords when rendered should be "comma-separated", as it was shown in the screenshot https://github.com/metanorma/metanorma-ieee/issues/102#issuecomment-1186076728 .

**Comment by Intelligent2013** [comment] 2022-07-16 07:47
@ronaldtse I see what is happened.
Rendered PDF for 1127 - comma separated:
![image](https://user-images.githubusercontent.com/5559926/179345638-fbb01f85-26ad-4e31-8c09-9ae422553062.png)
xml:
```xml
<keyword>A-weighted sound level</keyword>
<keyword>commercial zone</keyword>
<keyword>community involvement</keyword>
<keyword>hazardous material</keyword>
...
```

Rendered PDF for 2874 - semicolon separated:
![image](https://user-images.githubusercontent.com/5559926/179345560-f3ef9de2-24ab-47dd-8230-364db7e60a1c.png)

The reason is in the document.adoc for 2874:
`:keywords: Hyperspace Transaction Protocol; HSTP; Spatial Web; Hyperspatial Modelling Language; HSML; Spatial Domain registry; Metaverse; Digital Twin; SSI; DID; Verifiable Credentials`
- `;` is using as separator, therefore xml contains only one `keyword` 'as-is':
```xml
<keyword>Hyperspace Transaction Protocol; HSTP; Spatial Web; Hyperspatial Modelling Language; HSML; Spatial Domain registry; Metaverse; Digital Twin; SSI; DID; Verifiable Credentials</keyword>
```

**Comment by Intelligent2013** [comment] 2022-07-16 07:48
I.e. currently, xslt put comma as the separator between `keyword`'s already.

**Comment by ronaldtse** [comment] 2022-07-16 08:10
Our guide (https://www.metanorma.org/author/ieee/authoring-guide/metadata/) says that in input to keywords is comma-delimited.

<img width="770" alt="Screenshot 2022-07-16 at 5 10 05 PM" src="https://user-images.githubusercontent.com/11865/179346503-db91edfb-d4bf-4273-8138-f3b82a70bdb2.png">

**Comment by ronaldtse** [comment] 2022-07-16 08:11
Thank you @Intelligent2013 -- I will update P2874 accordingly.

**Comment by ronaldtse** [comment] 2022-07-17 03:33
Fixed in https://github.com/metanorma/SWF-Corpus_and_IEEEP2874-D2/commit/0683685aeba620f53acdac97dc85fa87ed3dce1a , confirmed with screenshot:
<img width="445" alt="Screenshot 2022-07-17 at 12 33 44 PM" src="https://user-images.githubusercontent.com/11865/179382692-5c32bab6-85a4-471c-94be-d2fbcf09521c.png">

**Closed by ronaldtse** 2022-07-17 03:33 UTC
Labels: bug
